graph TD;
    services-->core;
    components-->elements;
    services-->io;
    components-->services;
    subscriptions-->stores;
    services-->stores;
    services-->subscriptions;
    components-->subscriptions;
    styles-->subscriptions;
    elements-->ui;
    components-->ui;
    styles-->ui;
    io-->window;
    ui-->window;
