#!/bin/bash

export PROJECT_NAME="agileavatars"
export SRC="./src"
export DATA="./data"
export MODULES="$SRC/modules"
export TESTS="./tests"
export TEST_PATTERN="$TESTS/**/*.test.js"
export TEST_HELPERS="./test-helpers"
export TEST_WATCH_PATHS=("$SRC" "$TESTS" "$TEST_HELPERS")
export ESLINT_PATHS=("$SRC" "$TESTS")
export INDEXGEN_PATHS=("$MODULES")
export INDEXGEN_TYPE="esm"
export ITERMOCIL_TASKS=("edit" "test-watch" "indexgen-watch" "start")
export TASK_PATHS=("./tasks" "./tasks/defaults" "./tasks/lib")
export GITHUB_PAGES_PATH="./docs"
export README="./README.md"
export README_TEMPLATE="./README-TEMPLATE.md"
export COV_BRANCHES=100
export COV_LINES=100
export COV_FUNCTIONS=100
export COV_STATEMENTS=100
