#!/bin/bash

export PROJECT_NAME="Agile Avatars"
export WEB_HOST_NAME="agileavatars.com"

export BARREL_PATHS=("$MODULES" "./testing/modules")
export INDEXGEN_OPTIONS="--fullySpecified"
export README_GEN="./readme-gen/app.js"

export COV_BRANCHES=90
export COV_LINES=90
export COV_FUNCTIONS=90
export COV_STATEMENTS=90
