#!/usr/bin/env bash

export PROJECT_NAME="agileavatars"
export BUILD_OUTPUT="build_output"
export PACKAGE_OUTPUT="package_output"
export PUBLIC="public"
export PUBLIC_INDEX_HTML="$PUBLIC/index.html"
export PUBLIC_INDEX_JS="$PUBLIC/index.js"
export PUBLIC_IMAGES="$PUBLIC/img"
export SRC="src"
export TESTS="tests"
export TEST_HELPERS="test-helpers"
export INDEXGEN_PATHS="$SRC $TEST_HELPERS"

function task() {
    "tasks/$1" "${@:2}"
    EXIT_CODE=$?
    echo
    echo "exit code $EXIT_CODE"
}

time task $@
echo
exit $EXIT_CODE
