#!/bin/bash

. ./task-vars

function task() {
    for i in "${TASK_PATHS[@]}"; do [ -f "$i/$1" ] && TASK_FILE="$i/$1"; done
    echo "Task "$TASK_FILE" started"
    "$TASK_FILE" "${@:2}"
    EXIT_CODE=$?
    echo
    echo "Task "$TASK_FILE" completed with exit code $EXIT_CODE"
}

time task $@
echo
exit $EXIT_CODE
