#!/bin/bash
  
. ./task-vars

npx c8 --check-coverage \
--all \
--src "$SRC" \
--reporter=text-summary \
--reporter=lcov \
--branches $COV_BRANCHES \
--lines $COV_LINES \
--functions $COV_FUNCTIONS \
--statements $COV_STATEMENTS \
./task test
