#!/bin/bash
  
. ./task-vars

npx c8 \
--check-coverage \
--all \
--include "$SRC" \
--reporter=text-summary \
--reporter=lcov \
--reporter=html \
--branches $COV_BRANCHES \
--lines $COV_LINES \
--functions $COV_FUNCTIONS \
--statements $COV_STATEMENTS \
./tasks/test
