#!/bin/bash
  
. ./task-vars


./tasks/lib/itermocil-install   

cat > "itermocil.yml" <<EOF
windows:
  - name: $PROJECT_NAME
    root: $(pwd)
    layout: main-vertical
    panes:
EOF

for TASK_NAME in "${ITERMOCIL_TASKS[@]}"
do
for TASK_PATH in "${TASK_PATHS[@]}"; do [ -f "$TASK_PATH/$TASK_NAME" ] && TASK_FILE="$TASK_PATH/$TASK_NAME" && break; done
if [[ ! -z "$TASK_FILE" ]]; then
  cat >> "itermocil.yml" <<EOF
      - commands:
        - nvm use
        - $TASK_FILE
EOF
  fi
done

itermocil
