#!/bin/bash
  
. ./task-vars

[ ! -f "$README_TEMPLATE" ] && exit 0

node \
    --experimental-specifier-resolution=node \
    --input-type=module \
    - "$README_TEMPLATE" < ./tasks/lib/readme-file-generator.js > "$README"

npx --no doctoc \
    --maxlevel=2 \
    "$README"
