#!/usr/bin/env bash

set -e

npx task build-prod

PROFILE="prod"
PROFILE_OUTPUT="$BUILD_OUTPUT/$PROFILE"

CNAME="agileavatars.com"
DOCS="docs"

rm -rf "$DOCS"
mkdir -p "$DOCS"
cp -r $PROFILE_OUTPUT/* $DOCS/
echo $CNAME >> $DOCS/CNAME
