#!/usr/bin/env bash

STAGED_FILES=$(git diff --name-only --staged --diff-filter=d)
STAGED_DRAWIO=$(echo $STAGED_FILES | tr " " "\n" | grep -i ".drawio$")
STAGED_MERMAID=$(echo $STAGED_FILES | tr " " "\n" | grep -i ".mmd$")

if [ ! -z "$STAGED_DRAWIO" ]; then
    echo $STAGED_DRAWIO | xargs -n1 ./tasks/drawio-gen
fi

if [ ! -z "$STAGED_MERMAID" ]; then
    echo $STAGED_MERMAID | xargs -n1 ./tasks/mermaid-gen
fi
