#!/usr/bin/env bash

# Generates README.md

npx ejs ./README-TEMPLATE.md -o ./README.md \
    exampleComponentPath=src/lib/components/tag-list/tag/components/tag-name.js \
    exampleElementPath=src/lib/elements/editable-span.js
