#!/usr/bin/env bash

# Generates index.html interpolated with metadata.

URL="https://agileavatars.com"
TITLE="Agile Avatars"
DESCRIPTION="Agile Avatars makes it quick and easy to know who's working on what with great looking avatars for your agile board. No more fiddling with Word or Google Docs making sure everything aligns just right. Simply drag and drop your images, make some adjustments, print, and laminate!"
AUTHOR="Matt Riley"
IMAGE="$URL/img/social.jpg"

cat > "$PUBLIC_INDEX_HTML" <<EOF
<head>
<title>$TITLE</title>
<meta name="title" content="$TITLE">
<meta name="description" content="$DESCRIPTION">
<meta name="author" content="$AUTHOR">
<meta name="url" content="$URL">

<meta property="og:type" content="website">
<meta property="og:url" content="$URL">
<meta property="og:title" content="$TITLE">
<meta property="og:description" content="$DESCRIPTION">
<meta property="og:image" content="$IMAGE">

<meta property="twitter:card" content="summary_large_image">
<meta property="twitter:url" content="$URL">
<meta property="twitter:title" content="$TITLE">
<meta property="twitter:description" content="$DESCRIPTION">
<meta property="twitter:image" content="$IMAGE">
</head>

<body>
<script src="./app.js"></script>
</body>
EOF
