#!/usr/bin/env bash

# Launches an iTerm window arrangement from the current working directory using itermocil.
# https://github.com/TomAnthony/itermocil

cat > "iTermocil.yml" <<EOF
windows:
  - name: $PROJECT_NAME
    root: $(pwd)
    layout: main-vertical
    panes:
      - commands:
        - nvm use
      - commands:
        - nvm use
        - ./task test-watch
      - commands:
        - nvm use
        - ./task start
      - commands:
        - nvm use
        - ./task indexjs-gen
EOF

itermocil
