#!/usr/bin/env bash

# Launches an iTerm window arrangement from the current working directory using itermocil.
# https://github.com/TomAnthony/itermocil

. ./env

cat > "iTermocil.yml" <<EOF
windows:
  - name: $PROJECT_NAME
    root: $(pwd)
    layout: main-vertical
    panes:
      - commands:
        - nvm use
      - commands:
        - nvm use
        - ./tasks/start
      - commands:
        - nvm use
        - ./tasks/indexgen
EOF

itermocil
