#!/usr/bin/env bash

# Builds a .tar.gz package for a given build profile.

. ./env

PROFILE="$1"

mkdir -p "$PACKAGE_OUTPUT"
tar -czvf "$PACKAGE_OUTPUT/$PROFILE.tar.gz" -C "$BUILD_OUTPUT/$PROFILE" .
