#!/usr/bin/env bash

# Minimum quality check for a commit.

set -e

STAGED_FILES=$(git diff --name-only --staged | tr -d '[:space:]')
STAGED_DOCS=$(echo $STAGED_FILES | grep .md$ | tr -d '[:space:]')

if [ -z "$STAGED_FILES" ]; then
    echo "No staged files. Skipping pre-commit."
    exit 0
fi

if [ "$STAGED_FILES" = "$STAGED_DOCS" ]; then
    echo "Only docs are staged. Skipping lint and test."
else
    ./tasks/lint
    ./tasks/cov-check
fi

if [ ! -z "$STAGED_DOCS" ]; then
      ./tasks/readme-gen
fi
