#!/usr/bin/env bash -i

# Generates README.md

README="README.md"

# Generate README.md from ejs template.
node ./tasks/readme-gen.js > $README

# Generate table of contents.
npx doctoc --maxlevel 2 $README 

git add $README
git add docs
