#!/usr/bin/env bash -i

# Generates README.md
# NOTE: Ensure draw.io is on the PATH.

README="README.md"

# Generate README.md from ejs template.
node ./tasks/readme-gen.js > $README

# Generate table of contents.
npx doctoc --maxlevel 2 $README 

# Export architecture diagram.
draw.io -x -f svg --crop -o "docs/readme/architecture.svg" "docs/readme/architecture.drawio" 

git add $README
git add docs
