#!/usr/bin/env bash

# Runs unit tests with coverage and opens the coverage report.

. ./env

npx nyc \
    --include "$SRC" \
    --report-dir "$COVERAGE_REPORT_DIR" \
    --reporter=text-summary \
    --reporter=html \
    ./tasks/test


open "$COVERAGE_REPORT_DIR/index.html"
