#!/usr/bin/env bash

# Runs unit tests with coverage and opens the coverage report.

. ./env

npx nyc \
    --include "$SRC" \
    --reporter=text-summary \
    --reporter=html \
    ./tasks/test


open "coverage/index.html"
