module.exports = {
    __modulename: 'tags',
    dataTransforms: require('./data-transforms'),
    adjustInstanceCounts: require('./adjust-instance-counts'),
    attachImageAsync: require('./attach-image-async'),
    buildTagInstance: require('./build-tag-instance'),
    buildTag: require('./build-tag'),
    changeTagInstanceRole: require('./change-tag-instance-role'),
    changeTagName: require('./change-tag-name'),
    getInstance: require('./get-instance'),
    insertFileAsync: require('./insert-file-async'),
    insertFileBatchAsync: require('./insert-file-batch-async'),
    insertGravatarAsync: require('./insert-gravatar-async'),
    insertGravatarBatchAsync: require('./insert-gravatar-batch-async'),
    insertTagInstance: require('./insert-tag-instance'),
    insertTag: require('./insert-tag'),
    removeTagInstance: require('./remove-tag-instance'),
    setupRolePropagation: require('./setup-role-propagation'),
    setupTagPropagation: require('./setup-tag-propagation'),
    sortInstances: require('./sort-instances')
};
