graph TD;
    services-->core;
    components-->elements;
    services-->io;
    components-->services;
    subscriptions-->stores;
    services-->stores;
    services-->subscriptions;
    styles-->subscriptions;
    components-->subscriptions;
    io-->window;
    elements-->window;